name: istio
generator: helm # Deprecated in fabrikate v1.0.0
type: helm # Replaces `generator` in fabrikate v1.0.0
path: "./tmp/istio-1.1.5/install/kubernetes/helm/istio"
hooks:
  before-install:
    - curl -Lv https://github.com/istio/istio/releases/download/1.1.5/istio-1.1.5-linux.tar.gz -o istio.tar.gz
    - mkdir -p tmp
    - tar xvf istio.tar.gz -C tmp
  after-install:
    - rm istio.tar.gz
subcomponents:
  - name: istio-namespace
    generator: static # Deprecated in fabrikate v1.0.0
    type: static # Replaces `generator` in fabrikate v1.0.0
    path: ./manifests
  - name: istio-crd # 1.1 split out CRDs to seperate chart
    generator: helm # Deprecated in fabrikate v1.0.0
    type: helm # Replaces `generator` in fabrikate v1.0.0
    path: "./tmp/istio-1.1.5/install/kubernetes/helm/istio-init"
